/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgame;

import javax.swing.JFrame;

/**
 *
 * @author siddharth
 */
public class unogame3 extends javax.swing.JFrame {

    /**
     * Creates new form unogame3
     */
    public unogame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 120, 50));

        jButton2.setText("DEAL CARDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 140, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ai2.JPG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 100, 100));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("AI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("PLAYER 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 90, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 190));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("OPEN CARD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, -1));

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton5.setText("HELP");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 120, 50));

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 120, 50));

        jButton7.setText("Display Winner");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 150, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel14.setText("card1");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 130, 190));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel15.setText("card2");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 130, 190));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 140, 190));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 140, 190));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 130, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 130, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 130, 180));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 130, 180));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 130, 180));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/card_back.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 130, 180));

        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 130, 170));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 180, 40));

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 180, 40));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 250, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ai1.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 100, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/q02th.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 652));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        unogame x = new unogame();
        x.setVisible(true);
        x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        unogame1 x = new unogame1();
        x.setVisible(true);
        x.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        unogame4 q  = new unogame4();
        q.setVisible(true);
        q.setSize(400,250);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    int size1=0;
    int size2=0;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Deck d = new Deck();
        d.shuffle();
        Card c1 = d.deckOfcards.get(0);
        String str1 = c1.getValue();
        int x1 = c1.getInt(str1);
        String s1 = c1.getSuit();
        
        Card c2 = d.deckOfcards.get(1);
        String str2 = c2.getValue();
        int x2 = c2.getInt(str2);
        String s2 = c2.getSuit();
        
       
        Card c3 = d.deckOfcards.get(2);
        String str3 = c3.getValue();
        int x3 = c3.getInt(str3);
        String s3 = c3.getSuit();
        
        Card c4 = d.deckOfcards.get(3);
        String str4 = c4.getValue();
        int x4 = c4.getInt(str4);
        String s4 = c4.getSuit();
        
        Card c5 = d.deckOfcards.get(4);
        String str5 = c5.getValue();
        int x5 = c5.getInt(str5);
        String s5 = c5.getSuit();
        
        Card c6= d.deckOfcards.get(5);
        String str6 = c6.getValue();
        int x6 = c6.getInt(str6);
        String s6 = c6.getSuit();
        
        Card c7 = d.deckOfcards.get(6);
        String str7 = c7.getValue();
        int x7 = c7.getInt(str7);
        String s7 = c7.getSuit();
        
        Card c8 = d.deckOfcards.get(7);
        String str8 = c8.getValue();
        int x8 = c8.getInt(str8);
        String s8 = c8.getSuit();
        
        
        Card c9 = d.deckOfcards.get(8);
        String str9 = c9.getValue();
        int x9 = c9.getInt(str9);
        String s9 = c9.getSuit();
        
        
        Card c10 = d.deckOfcards.get(9);
        String str10 = c10.getValue();
        int x10 = c10.getInt(str10);
        String s10 = c10.getSuit();
        
        
        Card c11 = d.deckOfcards.get(10);
        String str11 = c11.getValue();
        int x11 = c11.getInt(str11);
        String s11 = c11.getSuit();
        
        
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c1.getImg())));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c2.getImg())));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c3.getImg())));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c4.getImg())));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c5.getImg())));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c6.getImg())));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c7.getImg())));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c8.getImg())));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c9.getImg())));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c10.getImg())));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+c11.getImg())));
     
        
     if(s11.equals(s1) || s11.equals(s2) || s11.equals(s3) || s11.equals(s4) || s11.equals(s5)) {
    size1=size1+10;
    jLabel20.setText( "Player Score="+size1);
    //jLabel20.setText( "Player Score="+size2);
    //jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winner2.png")));
    }
     
     if (x11==x1 || x11==x2 || x11==x3 || x11==x4 || x11==x5)
     {
       size1=size1+20;
       jLabel20.setText( "Player Score="+size1); 
     }
     
     if(s11.equals(s6) || s11.equals(s7) || s11.equals(s8) || s11.equals(s9) || s11.equals(s10)) {
    size2=size2+10;
    jLabel19.setText( "AI Score="+size2);
   // jLabel19.setText( "AI Score="+size1);
   // jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/winner1.png")));
    }
     
     if (x11==x6 || x11==x7 || x11==x8 || x11==x9 || x11==x10)
     {
    size2=size2+20;
    jLabel19.setText( "AI Score="+size2);
     }
     
     if (size1 >= 200)
     {
        unogame4 q  = new unogame4();
        q.setVisible(true);
        q.setSize(400,250);   
     }
     
     if (size2 >=200)
     {
        unogame5 q1  = new unogame5();
        q1.setVisible(true);
        q1.setSize(400,250); 
     }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unogame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unogame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unogame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unogame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new unogame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
